TOKEN = '7036098567:AAEW7SccjkpJVjmmhqM6zB2Yd7HcfTtmby4'
FOLDER_ID = "b1g3bcb59cje2qfhu2lr"
IAM_TOKEN = 't1.9euelZqOzsqQkYzGmZ2ZxpzIxpOTyu3rnpWaip7OnZWYzpLPmZKXjs6bjJ7l8_cTFHdN-e9PZ2ZD_d3z91NCdE35709nZkP9zef1656Vmo-Kz5XHysfMycvKjo2VlZad7_zF656Vmo-Kz5XHysfMycvKjo2VlZadveuelZqKlZmRjZLJyJWdj5uQzMaJy7XehpzRnJCSj4qLmtGLmdKckJKPioua0pKai56bnoue0oye.EYfdsB0d3Crjf8jakVgQu5hWXG_XbCCleM_y-v9z64QDzPzUQ5pupuhLr63OqkIt9nKVW51IcagbUpYzp-SgAA'
filename="log_file.txt"
MAX_USERS = 3
MAX_GPT_TOKENS = 120
COUNT_LAST_MSG = 4
TOKENIZE_URL = "https://llm.api.cloud.yandex.net/foundationModels/v1/tokenizeCompletion"
GPT_MODEL = 'yandexgpt-lite'
GPT_URL = "https://llm.api.cloud.yandex.net/foundationModels/v1/completion"
MAX_USER_STT_BLOCKS =15
MAX_USER_TTS_SYMBOLS = 5_000
MAX_USER_GPT_TOKENS = 3_000
DB_FILE = 'messages.db'
SYSTEM_PROMPT = [{'role': 'system', 'text': 'Будь добрым другом пользователя'}]
LOGS = 'creds/logs.log'
